spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistemafinac?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
#    jpa:
#        show-sql: true esse comendo mostra como é feito a pesquisa do SQL mas sem padrão SPRING

springdoc.swagger-ui.path: /swagger-ui
springdoc.swagger-ui.disable-swagger-default-url: true

# Esse metodo serve para deixa as pesquisas dentro padrão SPRING e  curso falou até melhor em perfomace
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG

server:
  servlet:
    context-path: /sistemafinac


